class DataStorageError {
    public static let CloseTable: String = "CLOSE_TABLE_ERROR"
    public static let CreateTable: String = "CREATE_TABLE_ERROR"
    public static let CreateTableStatement: String = "CREATE_TABLE_STATEMENT_ERROR"
    public static let DatabaseNotFound: String = "DATABASE_NOT_FOUND_ERROR"
    public static let Delete: String = "DELETE_ERROR"
    public static let DeleteStatement: String = "DELETE_STATEMENT_ERROR"
    public static let DropTable: String = "DROP_TABLE_ERROR"
    public static let DropTableStatement: String = "DROP_TABLE_STATEMENT_ERROR"
    public static let EmptyDatabaseName: String = "EMPTY_DATABASE_NAME_ERROR"
    public static let EmptyKey: String = "EMPTY_KEY_ERROR"
    public static let EmptyTable: String = "EMPTY_TABLE_ERROR"
    public static let EmptyValue: String = "EMPTY_VALUE_ERROR"
    public static let InsertOrReplace: String = "INSERT_OR_REPLACE_ERROR"
    public static let InsertOrReplaceStatement: String = "INSERT_OR_REPLACE_STATEMENT_ERROR"
    public static let JsonParse: String = "JSON_PARSE_ERROR"
    public static let JsonStringify: String = "JSON_STRINGIFY_ERROR"
    public static let KeyNotFound: String = "KEY_NOT_FOUND_ERROR";
    public static let OpenDatabase: String = "OPEN_DATABASE_ERROR"
    public static let RemoveDatabase: String = "REMOVE_ERROR"
    public static let Select: String = "SELECT_ERROR"
    public static let SelectStatement: String = "SELECT_STATEMENT_ERROR"
    public static let TableNotFound: String = "TABLE_NOT_FOUND_ERROR"
}
