export enum DataStorageError {
    CloseTable = "CLOSE_TABLE_ERROR",
    CreateTable = "CREATE_TABLE_ERROR",
    CreateTableStatement = "CREATE_TABLE_STATEMENT_ERROR",
    DatabaseNotFound = "DATABASE_NOT_FOUND_ERROR",
    Delete = "DELETE_ERROR",
    DeleteStatement = "DELETE_STATEMENT_ERROR",
    DropTable = "DROP_TABLE_ERROR",
    DropTableStatement = "DROP_TABLE_STATEMENT_ERROR",
    EmptyDatabaseName = "EMPTY_DATABASE_NAME_ERROR",
    EmptyKey = "EMPTY_KEY_ERROR",
    EmptyTable = "EMPTY_TABLE_ERROR",
    EmptyValue = "EMPTY_VALUE_ERROR",
    InsertOrReplace = "INSERT_OR_REPLACE_ERROR",
    InsertOrReplaceStatement = "INSERT_OR_REPLACE_STATEMENT_ERROR",
    JsonParse = "JSON_PARSE_ERROR",
    JsonStringify = "JSON_STRINGIFY_ERROR",
    KeyNotFound = "KEY_NOT_FOUND_ERROR",
    OpenDatabase = "OPEN_DATABASE_ERROR",
    RemoveDatabase = "REMOVE_ERROR",
    Select = "SELECT_ERROR",
    SelectStatement = "SELECT_STATEMENT_ERROR",
    TableNotFound = "TABLE_NOT_FOUND_ERROR"
}
